default["gravitybackup"]["chefvm"] = "chef-server"
default["gravitybackup"]["chefip"] = "169.254.123.2"
default["gravitybackup"]["vmdiskloc"] = "/opt/rpcs/chef-server.qcow2"
default["gravitybackup"]["vmxmlloc"] = "/opt/rpcs/chef-server.xml"
default["gravitybackup"]["backupdir"] = "/var/chef-backup"
default["gravitybackup"]["corenum"] = "4"
default["gravitybackup"]["vcorenum"] = "2"
